# Copyright 2020 The OpenTracing Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2.1

common: &common
  parameters:
    jdk:
      type: enum
      enum: ["8", "11"]
    image:
      type: enum
      enum: ["jdk8:0.1.1", "openjdk:11-jdk-stretch"]
  docker:
    - image: circleci/<< parameters.image >>

jobs:
  install:
    <<: *common
    steps:
      - checkout
      - restore_cache:
          keys:
            - specialagent-{{ checksum "pom.xml" }}-{{ .Branch }}-{{ .Revision }}
            - specialagent-{{ checksum "pom.xml" }}-{{ .Branch }}
            - specialagent-{{ checksum "pom.xml" }}
      - run:
          name: Installing
          no_output_timeout: 20m
          command: |
            mkdir -p << parameters.jdk >> && mv * << parameters.jdk >> || true
            cd << parameters.jdk >>
            mv .m2 ~ || mkdir -p ~/.m2
            rm -rf ~/.m2/repository/io/opentracing/contrib/specialagent && cp settings.xml ~/.m2/settings.xml
            export MAVEN_OPTS="-Xms64M -Xmx1600M -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
            mvn -version || sudo bash -c "wget https://downloads.apache.org/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz && tar -zxf apache-maven-3.5.4-bin.tar.gz -C /usr/local/ && ln -s /usr/local/apache-maven-3.5.4/bin/mvn /usr/bin/mvn"
            ls /usr/lib/x86_64-linux-gnu/libatomic.so.1 || sudo bash -c "apt-get -y update && apt-get -y install libatomic1"
            mvn -B -P test --fail-at-end -Dsilent dependency:go-offline || true
            if [ "$CIRCLE_BRANCH" = "master" ] &&
               [ "$CIRCLE_PULL_REQUEST" = "" ] &&
               [ "<< parameters.jdk >>" = "jdk8:0.1.1" ]; then
              echo "Installing with reports"
              mvn -e -B -P report install
              mvn -e -B -DrepoToken=$REPO_TOKEN coveralls:report
            else
              echo "Installing without reports"
              mvn -e -B install
            fi
            mvn -e -B -Dassemble install
            mv ~/.m2 .
      - save_cache:
          key: specialagent-{{ checksum "<< parameters.jdk >>/pom.xml" }}-{{ .Branch }}-{{ .Revision }}
          paths: << parameters.jdk >>/.m2
      - persist_to_workspace:
          root: .
          paths:
            - << parameters.jdk >>
  test:
    <<: *common
    parallelism: 4
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Testing
          no_output_timeout: 20m
          command: |
            cd << parameters.jdk >>
            mv .m2 ~
            mvn -version || sudo bash -c "wget https://downloads.apache.org/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz && tar -zxf apache-maven-3.5.4-bin.tar.gz -C /usr/local/ && ln -s /usr/local/apache-maven-3.5.4/bin/mvn /usr/bin/mvn"
            ls /usr/lib/x86_64-linux-gnu/libatomic.so.1 || sudo bash -c "apt-get -y update && apt-get -y install libatomic1"
            export MAVEN_OPTS="-Xms64M -Xmx1600M -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
            circleci tests glob "test/*/pom.xml" | sed 's/\/pom.xml//' | awk '{print "mvn -e -B -P test -pl " $1 " -amd integration-test"}' | circleci tests split > /tmp/tests-to-run
            bash -c "$(cat /tmp/tests-to-run)"
  deploy:
    <<: *common
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploying
          no_output_timeout: 20m
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ] &&
               [ "$CIRCLE_PULL_REQUEST" = "" ]; then
              cd << parameters.jdk >>
              mv .m2 ~
              mvn -version || sudo bash -c "wget https://downloads.apache.org/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz && tar -zxf apache-maven-3.5.4-bin.tar.gz -C /usr/local/ && ln -s /usr/local/apache-maven-3.5.4/bin/mvn /usr/bin/mvn"
              ls /usr/lib/x86_64-linux-gnu/libatomic.so.1 || sudo bash -c "apt-get -y update && apt-get -y install libatomic1"
              eval "echo $SECRET | base64 -d | bzip2 -dc | gpg --import --no-tty --batch --yes" &> /dev/null
              export GPG_TTY=$(tty)
              export MAVEN_OPTS="-Xms64M -Xmx1600M -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
              mvn -e -B -Dassemble -P deploy deploy
            fi

workflows:
  version: 2
  build:
    jobs:
      - install:
          name: install-jdk8
          jdk: "8"
          image: "jdk8:0.1.1"
      - install:
          name: install-jdk11
          jdk: "11"
          image: "openjdk:11-jdk-stretch"
      - test:
          name: test-jdk8
          jdk: "8"
          image: "jdk8:0.1.1"
          requires:
            - install-jdk8
      - test:
          name: test-jdk11
          jdk: "11"
          image: "openjdk:11-jdk-stretch"
          requires:
            - install-jdk11
      - deploy:
          name: deploy
          jdk: "8"
          image: "jdk8:0.1.1"
          requires:
            - test-jdk8
            - test-jdk11